name: Docker Image hangman API CD (using Docker actions)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: hangman-api/package-lock.json
    - name: build
      working-directory: ./hangman-api
      run: |
        npm ci
        npm run build --if-present
    - uses: actions/upload-artifact@v6
      with:
        name: build-code
        path: hangman-api/dist/

  # delivery:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - uses: actions/checkout@v6
  #   - uses: actions/download-artifact@v7
  #     with:
  #       name: build-code
  #       path: hangman-api/dist/
  #   - name: Build and Push Docker Image
  #     working-directory: ./hangman-api
  #     env:
  #       DOCKER_USER: "jaimesalas" # <your-docker-username>
  #       DOCKER_REPOSITORY: "hangman-api"
  #       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #     run: | 
  #       echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
  #       image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
  #       docker build -t $image -f Dockerfile.workflow .
  #       docker push $image

  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Download dist folder as artifact
        uses: actions/download-artifact@v7
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          # registry: by default is set to Docker Hub
          username: jtrillo # <your_docker_username>
          password:  ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./hangman-api
          push: true
          tags: jtrillo/hangman-api-actions:latest # <your_docker_username>
          file: ./hangman-api/Dockerfile.workflow
